package com.medical.ui.panels;
import com.medical.ui.dialogs.MedecinDialog;import com.medical.ui.models.*;import com.medical.ui.utils.*;import javax.swing.*;import javax.swing.border.EmptyBorder;import java.awt.*;import java.util.Arrays;
public class MedecinPanel extends JPanel{private final ApiClient api;private final MedecinTableModel model=new MedecinTableModel();private final JTable table=new JTable(model);private final JLabel status;public MedecinPanel(ApiClient a,JLabel s){api=a;status=s;setLayout(new BorderLayout(12,12));setBorder(new EmptyBorder(4,4,4,4));add(toolbar(),BorderLayout.NORTH);UiStyle.table(table);table.setAutoCreateRowSorter(true);RowActionCell.install(table,4,this::editRow,this::deleteRow);add(UiStyle.card(new JScrollPane(table)),BorderLayout.CENTER);refresh();}
private JToolBar toolbar(){JToolBar b=new JToolBar();b.setFloatable(false);b.setBorder(new EmptyBorder(4,0,4,0));b.add(UiStyle.title("Médecins"));b.add(Box.createHorizontalStrut(18));JButton a=new JButton("＋  Ajouter un médecin"),r=new JButton("↻  Actualiser");UiStyle.primaryButton(a);UiStyle.secondaryButton(r);a.addActionListener(e->add());r.addActionListener(e->refresh());b.add(a);b.add(Box.createHorizontalStrut(8));b.add(r);return b;}
private void refresh(){new SwingWorker<Medecin[],Void>(){protected Medecin[]doInBackground()throws Exception{return api.get("/api/medecins",Medecin[].class);}protected void done(){try{model.setData(Arrays.asList(get()));status.setText("  Liste des médecins actualisée");}catch(Exception e){error(e);}}}.execute();}
private void add(){MedecinDialog d=new MedecinDialog(SwingUtilities.getWindowAncestor(this),null);d.setVisible(true);if(!d.isOk())return;run(()->api.post("/api/medecins",new Medecin(d.code(),d.nom(),d.prenom(),d.grade()),Medecin.class));}
private void editRow(int row){Medecin o=model.getAt(row);MedecinDialog d=new MedecinDialog(SwingUtilities.getWindowAncestor(this),o);d.setVisible(true);if(!d.isOk())return;run(()->api.put("/api/medecins/"+api.encode(o.codeMed()),new Medecin(d.code(),d.nom(),d.prenom(),d.grade()),Medecin.class));}
private void deleteRow(int row){Medecin x=model.getAt(row);if(JOptionPane.showConfirmDialog(this,"Supprimer le médecin « "+x.codeMed()+" » ?","Confirmation",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE)!=JOptionPane.YES_OPTION)return;new SwingWorker<Void,Void>(){protected Void doInBackground()throws Exception{api.delete("/api/medecins/"+api.encode(x.codeMed()));return null;}protected void done(){try{get();refresh();status.setText("  Médecin supprimé");}catch(Exception e){error(e);}}}.execute();}
private interface Task{Object run()throws Exception;}private void run(Task t){new SwingWorker<Object,Void>(){protected Object doInBackground()throws Exception{return t.run();}protected void done(){try{get();refresh();status.setText("  Opération réalisée avec succès");}catch(Exception e){error(e);}}}.execute();}private void error(Exception e){Throwable x=e instanceof java.util.concurrent.ExecutionException&&e.getCause()!=null?e.getCause():e;status.setText("  Erreur : "+x.getMessage());JOptionPane.showMessageDialog(this,x.getMessage(),"Erreur",JOptionPane.ERROR_MESSAGE);}}
